function cfg = carlaConfig()
% carlaConfig - CARLA connection/setup parameters, in the same struct-
% config style as simulationConfig.m/vehicleConfig.m/etc. This is the
% single place CARLA connection details live - nothing elsewhere in the
% repository should hardcode a CARLA host/port/path.
%
% STATUS: VERIFIED LIVE (Phase 9 live verification pass) - every value
% below was actually confirmed against a real, running CARLA server, not
% assumed. See docs/carla_integration.md for the full installation record
% and live verification evidence (spawn/state/control/response logs).
%
%   - CARLA 0.9.16 (Windows package), installed at
%     C:\Users\<user>\CARLA_0.9.16\ (outside the repo - CARLA is an
%     external tool, not project source).
%   - CARLA 0.9.16 requires Python 3.7-3.12 (confirmed from CARLA's own
%     docs); this project's default Python is 3.13, so a DEDICATED,
%     isolated virtual environment was created at
%     C:\Users\<user>\carla_venv\ using a separately-installed Python
%     3.12.10 (via winget, user-scoped - the system/project default
%     Python 3.13 was never modified or downgraded). CARLA's own bundled
%     wheel (PythonAPI/carla/dist/carla-0.9.16-cp312-cp312-win_amd64.whl)
%     was installed into that venv - NOT the PyPI `carla` package, which
%     only publishes the old 0.9.5 release.
%   - MATLAB must point pyenv at that venv's python.exe BEFORE any py.*
%     call in the session (pyenv cannot change after Python loads):
%       pyenv('Version', 'C:\Users\<user>\carla_venv\Scripts\python.exe');
%     This project's own regression tests/scenarios never do this and
%     always run against the default Python 3.13 - confirmed to still
%     work with zero CARLA dependency.
%   - Server launched headless (no interactive display available) via:
%       CarlaUE4.exe -RenderOffScreen -carla-server -nosound
%     Boots in ~20-30s; default map on launch was Town10HD_Opt.
%   - Two TCP ports are used by CARLA (2000 default RPC port used here,
%     2001 as CARLA's secondary streaming port - both must be reachable;
%     only 2000 is configured here since the Python client only takes one
%     port and negotiates the second internally).
%
% Schema:
%   cfg.host              string, CARLA server host
%   cfg.port               integer, CARLA RPC port
%   cfg.timeoutSeconds     [s] client connection timeout
%   cfg.carlaVersion       string, the CARLA version this config was
%                          verified against
%   cfg.pythonExecutable   path to the dedicated CARLA-compatible Python
%                          venv's interpreter (pass to pyenv('Version',...)
%                          before connecting)
%   cfg.carlaPythonApiPath path to the installed CARLA release's
%                          PythonAPI/carla/dist directory (source of the
%                          wheel actually installed - kept for reference/
%                          reinstallation, not read at runtime)
%   cfg.mapName            CARLA map/town loaded by the server at launch
%   cfg.egoBlueprint       CARLA blueprint id for the ego vehicle
%   cfg.spawnPointIndex    integer index into the map's recommended spawn
%                          points, for a deterministic spawn; 1-based to
%                          match MATLAB convention, converted to the
%                          Python API's 0-based indexing inside
%                          carla_adapter.py
%
% Phase 10 additions - sensor sub-configs (camera/lidar/radar). Mount
% offsets are in the vehicle's own local frame (x=forward, y=right,
% z=up, meters; pitch/yaw/roll in degrees), matching CARLA's attach_to
% convention exactly - see carla_adapter.py's attach_camera/attach_lidar/
% attach_radar. Values below are reasonable, laptop-friendly defaults,
% not tuned against any specific sensor spec sheet.
%   cfg.camera.width/height/fov, mountX/Y/Z, mountPitch/Yaw/Roll
%   cfg.lidar.channels/range/pointsPerSecond/rotationFrequency/
%       upperFov/lowerFov, mountX/Y/Z, mountPitch/Yaw/Roll
%   cfg.radar.horizontalFov/verticalFov/range/pointsPerSecond,
%       mountX/Y/Z, mountPitch/Yaw/Roll

cfg = struct( ...
    'host',               'localhost', ...
    'port',               2000, ...
    'timeoutSeconds',     10.0, ...
    'carlaVersion',       '0.9.16', ...
    'pythonExecutable',   'C:\Users\ADITYA\carla_venv\Scripts\python.exe', ...
    'carlaPythonApiPath', 'C:\Users\ADITYA\CARLA_0.9.16\PythonAPI\carla\dist', ...
    'mapName',            'Town10HD_Opt', ...
    'egoBlueprint',       'vehicle.tesla.model3', ...
    'spawnPointIndex',    1 ...
);

cfg.camera = struct( ...
    'width',       640, ...
    'height',      480, ...
    'fov',         90.0, ...
    'mountX',      1.5, ...
    'mountY',      0.0, ...
    'mountZ',      2.0, ...
    'mountPitch',  0.0, ...
    'mountYaw',    0.0, ...
    'mountRoll',   0.0 ...
);

cfg.lidar = struct( ...
    'channels',          32, ...
    'range',             50.0, ...
    'pointsPerSecond',   100000, ...
    'rotationFrequency', 10.0, ...
    'upperFov',          10.0, ...
    'lowerFov',          -30.0, ...
    'mountX',            0.0, ...
    'mountY',            0.0, ...
    'mountZ',            2.2, ...
    'mountPitch',        0.0, ...
    'mountYaw',          0.0, ...
    'mountRoll',         0.0 ...
);

cfg.radar = struct( ...
    'horizontalFov',   30.0, ...
    'verticalFov',     10.0, ...
    'range',           70.0, ...
    'pointsPerSecond', 1500, ...
    'mountX',          2.0, ...
    'mountY',          0.0, ...
    'mountZ',          1.0, ...
    'mountPitch',      0.0, ...
    'mountYaw',        0.0, ...
    'mountRoll',       0.0 ...
);

end
