function ego = createEgoState()
% createEgoState - schema/constructor for the ego vehicle state struct.
%
% Schema:
%   ego.x          [m]   world-frame x position (rear axle or CoG, TBD in Phase 1)
%   ego.y          [m]   world-frame y position
%   ego.yaw        [rad] heading
%   ego.velocity   [m/s] longitudinal speed
%   ego.steering   [rad] current steering angle
%   ego.timestamp  [s]   simulation time of this state

ego = struct( ...
    'x',          0, ...
    'y',          0, ...
    'yaw',        0, ...
    'velocity',   0, ...
    'steering',   0, ...
    'timestamp',  0 ...
);

end
