function cfg = plannerConfig()
% plannerConfig - local/adaptive planner tuning parameters (stub, Phase 0).
%
% Schema:
%   cfg.numCandidateTrajectories          number of candidate trajectories sampled per replan
%   cfg.costWeights.collisionRisk         weight: proximity/likelihood of collision
%   cfg.costWeights.obstacleClearance     weight: distance margin to nearest obstacle
%   cfg.costWeights.pathDeviation         weight: deviation from reference/global path
%   cfg.costWeights.curvature             weight: trajectory curvature (ride comfort/feasibility)
%   cfg.costWeights.speedChange           weight: acceleration/jerk penalty
%   cfg.costWeights.uncertainty           weight: prediction-uncertainty penalty
%   cfg.ttcThresholds.warning  [s]        TTC below this triggers a caution behavior
%   cfg.ttcThresholds.critical [s]        TTC below this triggers emergency replanning/braking
%   cfg.replanTriggers.*                  boolean flags for what forces an immediate replan

cfg = struct();

cfg.numCandidateTrajectories = 15;

cfg.costWeights = struct( ...
    'collisionRisk',     5.0, ...
    'obstacleClearance', 2.0, ...
    'pathDeviation',     1.0, ...
    'curvature',         1.0, ...
    'speedChange',       0.5, ...
    'uncertainty',       1.5 ...
);

cfg.ttcThresholds = struct( ...
    'warning',  3.0, ...
    'critical', 1.5 ...
);

cfg.replanTriggers = struct( ...
    'onNewObstacle',       true, ...
    'onTrackLost',         true, ...
    'onTTCBelowWarning',   true, ...
    'onGlobalPathBlocked', true ...
);

end
