function cfg = sensorConfig()
% sensorConfig - per-sensor simulation parameters for camera/lidar/radar.
% Not part of the original Phase 0 file list (only simulationConfig/
% vehicleConfig/plannerConfig were named for config/) - added here for the
% same reason createAgent.m/createEgoState.m were split out: these tuning
% values don't belong crammed into an unrelated config file.
%
% Schema (per sensor): maxRange [m], fov [rad] (full field of view, centered
% on ego heading), detectionProbability (chance a real in-range/in-FOV agent
% is actually detected this frame), positionNoiseStd [m] (Gaussian noise
% added to ground-truth position), and sensor-specific extras.

cfg.camera = struct( ...
    'maxRange',             40, ...
    'fov',                  deg2rad(120), ...
    'detectionProbability', 0.95, ...
    'positionNoiseStd',     0.4, ...   % monocular depth estimation is imprecise
    'confidenceBase',       0.9 ...
);

cfg.lidar = struct( ...
    'maxRange',             60, ...
    'fov',                  deg2rad(180), ...
    'detectionProbability', 0.98, ...
    'positionNoiseStd',     0.08, ...  % lidar's strength: precise range/position
    'confidenceBase',       0.9 ...
);

cfg.radar = struct( ...
    'maxRange',             100, ...
    'fov',                  deg2rad(30), ...  % narrow forward-facing beam, typical of automotive radar
    'detectionProbability', 0.9, ...
    'positionNoiseStd',     1.2, ...   % radar's weakness: poor angular resolution
    'velocityNoiseStd',     0.15, ...  % radar's strength: doppler velocity is precise
    'confidenceBase',       0.85 ...
);

end
